<?php

/**
 * Implements hook_install().
 */
function civihr_employee_portal_features_install() {

  // Init civi
  civicrm_initialize();

  // Create the partially Approved status
  $option_group = civicrm_api3('OptionGroup', 'get', [
    'sequential' => 1,
    'name' => "activity_status",
  ]);

  $option_value = civicrm_api3('OptionValue', 'create', [
    'sequential' => 1,
    'label' => "Partially Approved",
    'option_group_id' => $option_group['id'],
  ]);
}
