<?php

/**
 * @file
 * Module to load css and js resources from a directory
 */

/**
 * Includes CSS/JS resources onto a page
 *
 * @param string $extension_path
 *   Machine path of civicrm extension.
 * @param array $resources_uris
 *   An array of resources URIs relative to extension paths to be included
 */
function civicrm_resources_add_resources($extension_path, $resources_uris = []) {
  foreach ($resources_uris as $resources_uri) {
    _civicrm_resources_add_resource($extension_path, $resources_uri);
  }
}

/**
 * Loads resources from the given extension
 *
 * @param string $extension_full_name
 *   Machine name of civicrm extension.
 * @param array $files
 *   An array of resources URIs relative to extension paths to be included
 */
function civicrm_resources_load($extension_full_name, $resources_uris = []) {
  if (cache_get($extension_full_name, 'cache_civicrm_resources')) {
    $ext_path_cache = cache_get($extension_full_name, 'cache_civicrm_resources');
    $ext_path = $ext_path_cache->data;
  }
  else {
    civicrm_initialize();

    $ext_path = CRM_Extension_System::singleton()
      ->getMapper()
      ->keyToBasePath($extension_full_name);

    cache_set($extension_full_name, $ext_path, 'cache_civicrm_resources');
  }

  civicrm_resources_add_resources($ext_path, $resources_uris);
}

/**
 * Implements hook_flush_caches().
 */
function civicrm_resources_flush_caches() {
  return ['cache_civicrm_resources'];
}

/**
 * Includes CSS/JS resources onto a page
 *
 * @param string $extension_path
 *   Machine path of civicrm extension.
 * @param array $resources_uris
 *   Resource URI relative to extension paths to be included
 */
function _civicrm_resources_add_resource($extension_path, $resource_uri) {
  $resource_type = pathinfo($resource_uri)['extension'];
  $relative_to_drupal_extension_path = str_replace(DRUPAL_ROOT, '', $extension_path);
  $relative_to_drupal_resource_path = $relative_to_drupal_extension_path . '/' . $resource_uri;

  if ($resource_type === 'js') {
    drupal_add_js($relative_to_drupal_resource_path,  array('scope' => 'footer'));
  } else if ($resource_type === 'css') {
    drupal_add_css($relative_to_drupal_resource_path);
  } else {
    throw 'The resource type "' . $resource_type . '" is not supported';
  }
}
